---
# file: roles/elk/tasks/elasticsearch.yml

- name: ES apt repo
  apt_repository:
    repo="deb http://packages.elastic.co/elasticsearch/{{ elk_elasticsearch.version }}/{{ ansible_os_family|lower }} stable main"
    update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Install ES apt packages
  apt: name=elasticsearch update_cache=yes state=latest
  when: ansible_os_family == 'Debian'

- name: Create elasticsearch directory
  file: path={{ elk_elasticsearch.path }} state=directory mode=0755 owner=elasticsearch group=elasticsearch

- name: Curator PIP package
  pip: name=elasticsearch-curator state=latest

- name: ES config file
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root group=elasticsearch mode=0750
  notify: Restart elasticsearch

- name: ES logging file
  template:
    src=elasticsearch-logging.yml.j2
    dest=/etc/elasticsearch/logging.yml
    owner=root group=elasticsearch mode=0750
  notify: Restart elasticsearch

- name: Import logrotate
  copy:
     src=elasticsearch-logrotate
     dest=/etc/logrotate.d/elasticsearch
     owner=root
     group=root
     mode=0644

- name: Create cron for curator
  cron: name="clean up elasticsearch entries" minute="20" hour="0" job="/usr/local/bin/curator --host localhost delete indices --older-than 7 --time-unit days --timestring '\%Y.\%m.\%d' > /dev/null"
