---
# file: roles/grafana/handlers/main.yml

- name: Restart grafana
  service:
     name=grafana-server
     state=restarted
     enabled=yes

- name: Restart influxdb
  service:
     name=influxdb
     state=restarted
     enabled=yes

- name: Reload apache2
  service:
    name=apache2
    state=reloaded